/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObservatoryRouteImport } from './routes/observatory'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as EarthImpactRouteImport } from './routes/earth-impact'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ObservatoryRoute = ObservatoryRouteImport.update({
  id: '/observatory',
  path: '/observatory',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const EarthImpactRoute = EarthImpactRouteImport.update({
  id: '/earth-impact',
  path: '/earth-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/dataset': typeof DatasetRoute
  '/earth-impact': typeof EarthImpactRoute
  '/explainability': typeof ExplainabilityRoute
  '/forecast': typeof ForecastRoute
  '/mission': typeof MissionRoute
  '/observatory': typeof ObservatoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/dataset': typeof DatasetRoute
  '/earth-impact': typeof EarthImpactRoute
  '/explainability': typeof ExplainabilityRoute
  '/forecast': typeof ForecastRoute
  '/mission': typeof MissionRoute
  '/observatory': typeof ObservatoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/dataset': typeof DatasetRoute
  '/earth-impact': typeof EarthImpactRoute
  '/explainability': typeof ExplainabilityRoute
  '/forecast': typeof ForecastRoute
  '/mission': typeof MissionRoute
  '/observatory': typeof ObservatoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/architecture'
    | '/dataset'
    | '/earth-impact'
    | '/explainability'
    | '/forecast'
    | '/mission'
    | '/observatory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/architecture'
    | '/dataset'
    | '/earth-impact'
    | '/explainability'
    | '/forecast'
    | '/mission'
    | '/observatory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/architecture'
    | '/dataset'
    | '/earth-impact'
    | '/explainability'
    | '/forecast'
    | '/mission'
    | '/observatory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DatasetRoute: typeof DatasetRoute
  EarthImpactRoute: typeof EarthImpactRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  ForecastRoute: typeof ForecastRoute
  MissionRoute: typeof MissionRoute
  ObservatoryRoute: typeof ObservatoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/observatory': {
      id: '/observatory'
      path: '/observatory'
      fullPath: '/observatory'
      preLoaderRoute: typeof ObservatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earth-impact': {
      id: '/earth-impact'
      path: '/earth-impact'
      fullPath: '/earth-impact'
      preLoaderRoute: typeof EarthImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchitectureRoute: ArchitectureRoute,
  DatasetRoute: DatasetRoute,
  EarthImpactRoute: EarthImpactRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  ForecastRoute: ForecastRoute,
  MissionRoute: MissionRoute,
  ObservatoryRoute: ObservatoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
